"""change hobbies in questionary model

Revision ID: 093b56f06730
Revises: 6a8cb6ec0180
Create Date: 2023-09-08 11:33:02.239826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '093b56f06730'
down_revision = '6a8cb6ec0180'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_questionnaire_hobby',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hobby_name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_hobby',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('hobby_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['hobby_id'], ['user_questionnaire_hobby.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_questionnaire.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'hobby_id')
    )
    op.alter_column('user_questionnaire', 'firstname',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.drop_column('user_questionnaire', 'passion')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_questionnaire', sa.Column('passion', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('user_questionnaire', 'firstname',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.drop_table('user_hobby')
    op.drop_table('user_questionnaire_hobby')
    # ### end Alembic commands ###
