"""Add to_id to message, make text nullable, change field name

Revision ID: 4f21deed5f82
Revises: 51e208efbb6b
Create Date: 2023-10-07 23:29:47.123295

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4f21deed5f82'
down_revision = '51e208efbb6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('to_id', sa.Uuid(), nullable=False))
    op.add_column('message', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column(
        'message', 'text',
        existing_type=sa.VARCHAR(length=4096),
        nullable=True
    )
    op.create_foreign_key(
        None, 'message',
        'auth_user', ['to_id'], ['id'],
        ondelete='RESTRICT'
    )
    op.drop_column('message', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.alter_column('message', 'text',
                    existing_type=sa.VARCHAR(length=4096),
                    nullable=False)
    op.drop_column('message', 'updated_at')
    op.drop_column('message', 'to_id')
    # ### end Alembic commands ###
