"""add_message

Revision ID: 51e208efbb6b
Revises: c347c3783bc4
Create Date: 2023-09-28 21:42:34.011114

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from src.chat.util import MessageStatus

# revision identifiers, used by Alembic.
revision = "51e208efbb6b"
down_revision = "c347c3783bc4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("match_id", sa.Uuid(), nullable=False),
        sa.Column("from_id", sa.Uuid(), nullable=False),
        sa.Column("text", sa.String(length=4096), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sqlalchemy_utils.types.choice.ChoiceType(MessageStatus),
            nullable=False,
        ),
        sa.Column("captions", postgresql.ARRAY(sa.String()), nullable=True),
        sa.ForeignKeyConstraint(["from_id"], ["auth_user.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["match_id"], ["match.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("message")
    # ### end Alembic commands ###
