"""added index model black_list

Revision ID: 5400d9d74491
Revises: f00c794334ef
Create Date: 2023-07-29 13:17:28.972409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5400d9d74491'
down_revision = 'f00c794334ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('black_list_user_id_fkey', 'black_list_user', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('black_list_user_id_fkey', 'black_list_user', 'auth_user', ['id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
