"""Add age, unqique constraint quest, user_id=null

Revision ID: 5c47a192ce1d
Revises: 4f21deed5f82
Create Date: 2023-12-12 18:10:52.693682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c47a192ce1d'
down_revision = '4f21deed5f82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_questionnaire', sa.Column('age', sa.Integer(), nullable=False))
    op.create_unique_constraint('_user_id_uc', 'user_questionnaire', ['user_id'])
    op.alter_column('user_questionnaire', 'user_id',
                    existing_type=sa.UUID(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_id_uc', 'user_questionnaire', type_='unique')
    op.drop_column('user_questionnaire', 'age')
    op.alter_column('user_questionnaire', 'user_id',
                    existing_type=sa.UUID(),
                    nullable=True)
    # ### end Alembic commands ###
