"""empty message

Revision ID: 6460cd3ea105
Revises: 7cd34eae4fd8
Create Date: 2023-08-09 20:01:53.508137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6460cd3ea105"
down_revision = "7cd34eae4fd8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_like",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("liked_user_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("NOT(user_id = liked_user_id)", name="_user_like_cc"),
        sa.ForeignKeyConstraint(
            ["liked_user_id"], ["auth_user.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "liked_user_id", name="_user_like_uc"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_like")
    # ### end Alembic commands ###
