"""init models

Revision ID: 6a8cb6ec0180
Revises: 
Create Date: 2023-07-29 15:22:20.958378

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa
from src.questionary.params_choice import for_body_type, for_gender, for_goals, for_passion

# revision identifiers, used by Alembic.
revision = '6a8cb6ec0180'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('email', sa.String(length=50), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('is_superuser', sa.Boolean(), nullable=False),
                    sa.Column('is_verified', sa.Boolean(), nullable=False),
                    sa.Column('is_delete', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_auth_user_email'), 'auth_user', ['email'], unique=True)
    op.create_table('black_list_user',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('user_id', sa.Uuid(), nullable=False),
                    sa.Column('blocked_id', sa.Uuid(), nullable=False),
                    sa.ForeignKeyConstraint(['blocked_id'], ['auth_user.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('idx_user_to_block', 'black_list_user', ['user_id', 'blocked_id'], unique=True)
    op.create_table('match',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user1_id', sa.Uuid(), nullable=False),
                    sa.Column('user2_id', sa.Uuid(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['user1_id'], ['auth_user.id'], ondelete='RESTRICT'),
                    sa.ForeignKeyConstraint(['user2_id'], ['auth_user.id'], ondelete='RESTRICT'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('message',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('sender', sa.Uuid(), nullable=False),
                    sa.Column('receiver', sa.Uuid(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('message_text', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['receiver'], ['auth_user.id'], ),
                    sa.ForeignKeyConstraint(['sender'], ['auth_user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_message_id'), 'message', ['id'], unique=False)
    op.create_table('user_like',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Uuid(), nullable=False),
                    sa.Column('liked_user_id', sa.Uuid(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['liked_user_id'], ['auth_user.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
                    sa.PrimaryKeyConstraint('id', 'user_id', 'liked_user_id')
                    )
    op.create_index(op.f('ix_user_like_id'), 'user_like', ['id'], unique=False)
    op.create_table('user_questionnaire',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('firstname', sa.String(length=256), nullable=False),
                    sa.Column('lastname', sa.String(length=256), nullable=True),
                    sa.Column('gender', sqlalchemy_utils.types.choice.ChoiceType(for_gender), nullable=True),
                    sa.Column('photo', sa.String(), nullable=True),
                    sa.Column('country', sa.String(), nullable=True),
                    sa.Column('city', sa.String(), nullable=True),
                    sa.Column('latitude', sa.Numeric(precision=8, scale=5), nullable=True),
                    sa.Column('longitude', sa.Numeric(precision=8, scale=5), nullable=True),
                    sa.Column('about', sa.String(), nullable=True),
                    sa.Column('passion', sqlalchemy_utils.types.choice.ChoiceType(for_passion), nullable=True),
                    sa.Column('height', sa.Integer(), nullable=True),
                    sa.Column('goals', sqlalchemy_utils.types.choice.ChoiceType(for_goals), nullable=True),
                    sa.Column('body_type', sqlalchemy_utils.types.choice.ChoiceType(for_body_type), nullable=True),
                    sa.Column('is_visible', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['id'], ['auth_user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user_settings',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('subscriber', sa.DateTime(), nullable=True),
                    sa.Column('last_seen', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['id'], ['auth_user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    op.drop_table('user_questionnaire')
    op.drop_index(op.f('ix_user_like_id'), table_name='user_like')
    op.drop_table('user_like')
    op.drop_index(op.f('ix_message_id'), table_name='message')
    op.drop_table('message')
    op.drop_table('match')
    op.drop_index('idx_user_to_block', table_name='black_list_user')
    op.drop_table('black_list_user')
    op.drop_index(op.f('ix_auth_user_email'), table_name='auth_user')
    op.drop_table('auth_user')
    # ### end Alembic commands ###
