"""Changed the type hint for a column like

Revision ID: 88566986fa2a
Revises: caa5806332bf
Create Date: 2023-07-15 21:27:56.486822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88566986fa2a'
down_revision = 'caa5806332bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rating', 'like',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rating', 'like',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
