"""get_quests_logic

Revision ID: cf8221c9bee3
Revises: fa5f9699e17b
Create Date: 2024-03-01 12:58:31.735891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf8221c9bee3'
down_revision = 'fa5f9699e17b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_joint_rate',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id_1', sa.Uuid(), nullable=False),
    sa.Column('user_id_2', sa.Uuid(), nullable=False),
    sa.Column('joint_rate', sa.Integer(), nullable=False),
    sa.CheckConstraint('NOT(user_id_1 = user_id_2)', name='_user_joint_rate_cc'),
    sa.ForeignKeyConstraint(['user_id_1'], ['auth_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id_2'], ['auth_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id_1', 'user_id_2', name='_users_joint_rate_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_joint_rate')
    # ### end Alembic commands ###
