"""new_get_quest_rools

Revision ID: d11477116e69
Revises: 84f11c7d251e
Create Date: 2024-01-09 21:07:19.905174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd11477116e69'
down_revision = '84f11c7d251e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_questionnaire', sa.Column('is_prem', sa.Boolean(), nullable=False))
    op.add_column('user_questionnaire', sa.Column('quest_lists_per_day', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_questionnaire', 'quest_lists_per_day')
    op.drop_column('user_questionnaire', 'is_prem')
    # ### end Alembic commands ###
