"""new alg to get_quest_list

Revision ID: d725fd364884
Revises: fa5f9699e17b
Create Date: 2024-03-03 23:14:13.627860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd725fd364884'
down_revision = 'fa5f9699e17b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_questionnaire', sa.Column('rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_questionnaire', 'rate')
    # ### end Alembic commands ###
