"""Change user id column type int -> UUID

Revision ID: e0930ee6133d
Revises: dc48cb81011f
Create Date: 2023-07-28 00:07:03.494514

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e0930ee6133d'
down_revision = 'dc48cb81011f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_settings', 'black_list',
                    existing_type=sa.INTEGER(),
                    comment='Move to another table',
                    existing_nullable=True)

    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')

    op.execute('ALTER TABLE public.like DROP CONSTRAINT like_user_id_fkey')
    op.execute('ALTER TABLE public.like DROP CONSTRAINT like_liked_user_id_fkey')
    op.execute('ALTER TABLE match DROP CONSTRAINT match_user1_id_fkey')
    op.execute('ALTER TABLE match DROP CONSTRAINT match_user2_id_fkey')
    op.execute('ALTER TABLE message DROP CONSTRAINT message_receiver_fkey')
    op.execute('ALTER TABLE message DROP CONSTRAINT message_sender_fkey')
    op.execute('ALTER TABLE user_questionnaire DROP CONSTRAINT user_questionnaire_id_fkey')
    op.execute('ALTER TABLE user_settings DROP CONSTRAINT user_settings_id_fkey')
    op.execute('ALTER TABLE public.user ALTER COLUMN id DROP default')

    op.execute('ALTER TABLE public.like ALTER COLUMN user_id SET DATA TYPE varchar(36)')
    op.execute('ALTER TABLE public.like ALTER COLUMN liked_user_id SET DATA TYPE varchar(36)')
    op.execute('ALTER TABLE match ALTER COLUMN user1_id SET DATA TYPE varchar(36)')
    op.execute('ALTER TABLE match ALTER COLUMN user2_id SET DATA TYPE varchar(36)')
    op.execute('ALTER TABLE message ALTER COLUMN sender SET DATA TYPE varchar(36)')
    op.execute('ALTER TABLE message ALTER COLUMN receiver SET DATA TYPE varchar(36)')
    op.execute('ALTER TABLE user_questionnaire ALTER COLUMN id SET DATA TYPE varchar(36)')
    op.execute('ALTER TABLE user_settings ALTER COLUMN id SET DATA TYPE varchar(36)')
    op.execute('ALTER TABLE public.user ALTER COLUMN id SET DATA TYPE varchar(36)')

    op.execute('ALTER TABLE public.like ALTER COLUMN user_id SET DATA TYPE UUID USING (uuid_generate_v4())')
    op.execute('ALTER TABLE public.like ALTER COLUMN liked_user_id SET DATA TYPE UUID USING (uuid_generate_v4())')
    op.execute('ALTER TABLE match ALTER COLUMN user1_id SET DATA TYPE UUID USING (uuid_generate_v4())')
    op.execute('ALTER TABLE match ALTER COLUMN user2_id SET DATA TYPE UUID USING (uuid_generate_v4())')
    op.execute('ALTER TABLE message ALTER COLUMN sender SET DATA TYPE UUID USING (uuid_generate_v4())')
    op.execute('ALTER TABLE message ALTER COLUMN receiver SET DATA TYPE UUID USING (uuid_generate_v4())')
    op.execute('ALTER TABLE user_questionnaire ALTER COLUMN id SET DATA TYPE UUID USING (uuid_generate_v4())')
    op.execute('ALTER TABLE user_settings ALTER COLUMN id SET DATA TYPE UUID USING (uuid_generate_v4())')
    op.execute('ALTER TABLE public.user ALTER COLUMN id SET DATA TYPE UUID USING (uuid_generate_v4())')
    op.execute('ALTER TABLE public.user ALTER COLUMN id SET DEFAULT (uuid_generate_v4())')

    op.execute('ALTER TABLE public.like ADD CONSTRAINT like_user_id_fkey '
               'FOREIGN KEY (user_id) REFERENCES public.user (id) ON DELETE CASCADE')
    op.execute('ALTER TABLE public.like ADD CONSTRAINT like_liked_user_id_fkey '
               'FOREIGN KEY (liked_user_id) REFERENCES public.user (id) ON DELETE CASCADE')
    op.execute('ALTER TABLE match ADD CONSTRAINT match_user1_id_fkey '
               'FOREIGN KEY (user1_id) REFERENCES public.user (id) ON DELETE CASCADE')
    op.execute('ALTER TABLE match ADD CONSTRAINT match_user2_id_fkey '
               'FOREIGN KEY (user2_id) REFERENCES public.user (id) ON DELETE CASCADE')
    op.execute('ALTER TABLE message ADD CONSTRAINT message_receiver_fkey '
               'FOREIGN KEY (receiver) REFERENCES public.user (id) ON DELETE CASCADE')
    op.execute('ALTER TABLE message ADD CONSTRAINT message_sender_fkey '
               'FOREIGN KEY (sender) REFERENCES public.user (id) ON DELETE CASCADE')
    op.execute('ALTER TABLE user_questionnaire ADD CONSTRAINT user_questionnaire_id_fkey '
               'FOREIGN KEY (id) REFERENCES public.user (id) ON DELETE CASCADE')
    op.execute('ALTER TABLE user_questionnaire ADD CONSTRAINT user_settings_id_fkey '
               'FOREIGN KEY (id) REFERENCES public.user (id) ON DELETE CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_settings', 'black_list',
                    existing_type=sa.INTEGER(),
                    comment=None,
                    existing_comment='Move to another table',
                    existing_nullable=True)
    # ### end Alembic commands ###
