"""changed model black_list

Revision ID: f00c794334ef
Revises: 96f31b1e3b05
Create Date: 2023-07-29 12:57:45.803446

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f00c794334ef'
down_revision = '96f31b1e3b05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_user_to_block', 'black_list_user', ['user_id', 'blocked_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_to_block', table_name='black_list_user')
    # ### end Alembic commands ###
