"""new quest model

Revision ID: fa5f9699e17b
Revises: afd4c92e479a
Create Date: 2024-02-14 13:12:34.794659

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from src.questionnaire.params_choice import *

# revision identifiers, used by Alembic.
revision = 'fa5f9699e17b'
down_revision = 'afd4c92e479a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_questionnaire', 'age')
    op.add_column('user_questionnaire', sa.Column('sport', sqlalchemy_utils.types.choice.ChoiceType(SportType), nullable=False))
    op.add_column('user_questionnaire', sa.Column('smoking', sqlalchemy_utils.types.choice.ChoiceType(SmokingType), nullable=False))
    op.add_column('user_questionnaire', sa.Column('alcohol', sqlalchemy_utils.types.choice.ChoiceType(AlcoholType), nullable=False))
    op.add_column('user_questionnaire',  sa.Column('birthday', sa.Date(), nullable=False))
    op.drop_column('user_questionnaire', 'body_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_questionnaire', 'birthday')
    op.add_column('user_questionnaire', sa.Column('body_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user_questionnaire', sa.Column('age', sa.Integer(), nullable=True))
    op.drop_column('user_questionnaire', 'alcohol')
    op.drop_column('user_questionnaire', 'smoking')
    op.drop_column('user_questionnaire', 'sport')
    # ### end Alembic commands ###
