"""add new field for like

Revision ID: fbec8bc555f3
Revises: 6a8cb6ec0180
Create Date: 2023-09-06 15:13:20.472172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbec8bc555f3'
down_revision = '6a8cb6ec0180'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_like', sa.Column('is_like', sa.Boolean(), nullable=False))
    op.alter_column('user_questionnaire', 'firstname',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.add_column('user_settings', sa.Column('search_range_min', sa.Integer(), nullable=False))
    op.add_column('user_settings', sa.Column('search_range_max', sa.Integer(), nullable=False))
    op.add_column('user_settings', sa.Column('search_age_min', sa.Integer(), nullable=False))
    op.add_column('user_settings', sa.Column('search_age_max', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'search_age_max')
    op.drop_column('user_settings', 'search_age_min')
    op.drop_column('user_settings', 'search_range_max')
    op.drop_column('user_settings', 'search_range_min')
    op.alter_column('user_questionnaire', 'firstname',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.drop_column('user_like', 'is_like')
    # ### end Alembic commands ###
